name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
    - name: Checkout code
      uses: actions/checkout@v4
    - name: HeapTests
      id: HeapTests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: HeapTests
        setup-command: ''
        command: mvn test -Dtest=HeapTest
        timeout: 30
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HEAPTESTS_RESULTS: "${{steps.HeapTests.outputs.result}}"
      with:
        runners: HeapTests